### ISSUE TITLE
igb_receive, more then one packet at one function call

### ISSUE THREAD

**Issue by KnutSchrader** [Avnu/igb_avb#21]
API: 
int igb_receive(device_t *dev, unsigned int queue_index, 
                     struct igb_packet **received_packets, u_int32_t *count);

Question: Is it possible to receive more then one packet at once?, e.g.
count = 8, count = 16
The example "simple_rx" shows only one packet.
If possible, an code example would be very helpful.

**Comment by psykuter** [comment]
Since this is a custom scenario we will not post the required changes into the repository. However we developed some proof of concept, tested it and it seems to work and address your request. Therefore we will provide you with a detailed explanation of the needed alterations and you would have to introduce them on your own to the code. 

Generally speaking it is possible to receive more than 1 packet at a time.
The original code is not adapted to higher packet_count values (2 and more).

Sticking to the technicalities and particular lib/simple_rx methods: 
Igb_receive is function responsible for receiving and storing packages. Count defines number of packets that you want to save during single call function. Note, we pass in as argument the address of count variable and as a consequence work on the original variable, not copy. Igb_refresh and igb_process_rx methods use this value to determine the number of loop iterations. If you want to store more packets at the same time, you need to allocate an additional array. This is supposed to be an array of pointers and sent them to function and write packets to them. Inside the function you will have the ability to utilize count as the array index and write data to it.
   
Igb_refresh_buffers prepares buffers for further use and sets register E1000_RDT. The register is described as receive descriptor tail and should be updated correctly. (more information on the theory itself is available on pages 273-274 in I210 datasheet). In case of receiving more than 1 packet at a time you need to use more buffers and as a consequence you need to refresh more buffers for next use and shift tail by the right value. Over here one modification is required.
 
Igb_process_rx calls two previously mentioned functions and copies data from our table to file. You receive more packets and as a consequence have to write more data to file at once before you refresh buffers and receive the next packets. So new loop is required and count determines number of iterations (which is scaled to writing packets to file in fact).

The following changes in the current code are required for the PoC to work:
•	OpenAvnu/examples/simple_rx/simple_rx.c in function igb_process_rx
o	Change type igb_pkt from struct igb_packet* on struct igb_packet**  - pointer to pointer allows to allocate table of pointers
o	igb_pkt = (struct igb_packet **) calloc (count, sizeof(struct igb_packet *))  - dynamic allocation of the mentioned pointer array with the use of count. You get an array with count elements. Calloc allocates memory and zero-initalizes it. 
o	Change &igb_pkt into igb_pkt in call igb_receive(..., ..., igb_pkt, ...) and igb_refresh_buffers(..., ..., igb_pkt, ...) - Ensuring type compability. 
o	Add new variable uint32_t j and create a loop  for (j = 0; j < count; j++)  - in this loop we copy data to file
o	Igb_refresh_buffers(.., .., .., count) – change last parameter in function call, count instead of hardcoded 1.
o	Packet = igb_pkt[j]->vaddr - operator [] works similar to asterisk in this case, work on type (struct igb_packet *) and move through array
o	if (igb_pkt) { igb_refresh_buffers } - move on end new loop
o	Free(igb_pkt) instead igb_pkt = NULL - both versions are ok
 
•	OpenAvnu/lib/igb_avb/lib/igb.c in function igb_receive
o	Delete line with *received_packets = NULL - Calloc replaces it, so it's not needed.
o	Changed every occurrence *received_packets on received_packets[*count] - operator [] works similar to asterisk in this case, so we work on the same type and operator [*count] provides you the ability to move across subsequent array indexes

**Comment by jfornal** [comment]
There has been a detailed explanation of the POC and required changes provided to satisfy the request above. Can we close the issue then? Feel free to contact us in case of any potential code level problem while implementing those changes of course.

**Comment by KnutSchrader** [comment]
You can close the task. Thanks.
